### PR TITLE
chore(repo): dApp submission request

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

In issue #3025, we will introduce a feature that suggests OISY users submit an issue to have their dApps featured in the explorer. For this purpose, we need a template.

# Notes

This is a bare-bones template that will be refined, but it allows us to already embed a proper URL in the dApp.

# Changes

- Create template `dapp_submission_request.md`

### CODE REVIEW

**Review by loki344 — APPROVED** [review]
Thanks!

**Review by AntonioVentilii-DFINITY — APPROVED** [review]
LGTM!

Small doubt for me: shall "Dapp" be re-written as "dApp"? What is the "official" way to write this usually?

**Comment by peterpeterparker** [comment]
I would use "dApp" too but @Stefan-Berger-DFINITY used "Dapp"

**Comment by peterpeterparker** [comment]
Good catch, fixed the lower case.

**Pull request merged**
