### PR TITLE
refactor(frontend): rename AllTransactionsUi type

### PR DESCRIPTION
**Pull request by AntonioVentilii**
# Motivation

As suggested in https://github.com/dfinity/oisy-wallet/pull/3601#pullrequestreview-2440325251 , we rename type`AllTransactionsUi` for readability reasons.

### CODE REVIEW

**Comment by AntonioVentilii** [comment]
Any suggestion on better naming is welcomed

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Comment by AntonioVentilii** [comment]
[OISY-130]

**Comment by AntonioVentilii** [comment]
[OISY-130]

**Pull request merged**
