### PR TITLE
refactor(frontend): move metadata from .env file to JSON file

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

We would like to make the following metadata static:

- OISY_NAME
- OISY_ONELINER
- OISY_DESCRIPTION
- OISY_REPO_URL
- OISY_ALPHA_WARNING_URL

So, we move them to a JSON file to be used both by the `src` code and by the building scripts.

# Changes

- Create JSON file with metadata in `src/env` folder.
- Adapt `src` code constants to fetch JSON file.
- Adjust `html` and `manifest` file to use new metadata.
- Adjust building script to fetch JSON file.
- Clean `.env` files.

# Tests

1. On local replica, the constants are properly used. For example, in the i18n function replaceOisyPlaceholders:
Screenshot 2024-07-31 at 09 08 33

2. After `npm run build`, the html files and the manifest files are properly built:
```json
{
	"name": "Oisy Wallet",
	"short_name": "Oisy Wallet",
	"start_url": ".",
	"display": "standalone",
	"theme_color": "#33156A",
	"background_color": "#33156A",
	"description": "A multi-chain wallet powered by chainfusion",
	"orientation": "portrait-primary",
	"prefer_related_applications": false,
	"categories": ["finance"],
	"icons": [
		{
			"src": "favicons/icon-192x192.png",
			"sizes": "192x192",
			"type": "image/png"
		},
		{
			"src": "favicons/icon-512x512.png",
			"sizes": "512x512",
			"type": "image/png"
		}
	],
	"shortcuts": [
		{
			"name": "Ethereum",
			"url": "/",
			"icons": [{ "src": "/icons/eth.png", "type": "image/png", "sizes": "192x192" }]
		},
		{
			"name": "Internet Computer",
			"url": "/?network=ICP",
			"icons": [{ "src": "/icons/icp.png", "type": "image/png", "sizes": "192x192" }]
		}
	]
}

```

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
I would move the json file to `frontend/src/env`. I would also use zod to verify the JSON and create constants, loaded from the JSON, to replace the `VITE_OISY_...` usages. Finally I would cleanup the build scripts.

WDYT?

**Comment by AntonioVentilii-DFINITY** [comment]
On it! 

> Finally I would cleanup the build scripts.

I thought I did it in this PR, or you mean something else?

**Comment by peterpeterparker** [comment]
> or you mean something else?

Just in case there is still something to clean

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker ready for another review

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks

It's nicer!

**Pull request merged**
