### PR TITLE
feat(frontend): add loader for solana balances

### PR DESCRIPTION
**Pull request by loki344**
# Motivation

Implement solana balance service.

# Changes

- implement solana balance service

# Tests

Unit testing added for solana balance service

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
Please split the solution in separate PRs. The logic and UI presentation can be decoupled.

**Comment by loki344** [comment]
> Please split the solution in separate PRs. The logic and UI presentation can be decoupled.

moved UI logic to: https://github.com/dfinity/oisy-wallet/pull/4022

**Comment by loki344** [comment]
Converted to draft - not rdy yet

**Comment by loki344** [comment]
incorporated this branch in #4037, will close it

**Pull request closed without merging**
