### PR TITLE
refactor: as temporary precaution, we disable non-ICRC manage toggle

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

As temporary precaution we disable all non-ICRC manage toggle, until we are ok with the complete flow.

# To-Do

- [ ] Remove hard-coded condition to disable the toggle

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
Maybe rather:

```
// TODO: set to false and uncomment once we are OK with flow of show/hide ERC20 tokens
let disabled = true;
// $: disabled = !["icrc", "erc20"].includes(token.category);
```

**Comment by AntonioVentilii-DFINITY** [comment]
done, but probably we will need to revisit the logic to disable, since we haven't defined yet which one we enable/disable about etherem/erc20 , right

**Comment by peterpeterparker** [comment]
Definitely we should review before merging but, I think there is a good chance it's correct 🤞

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Pull request merged**
