### PR TITLE
feat(frontend): Bubble loading prop of ButtonHero

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

We want to slowly bubble the loading prop of `ButtonHero`, so that we can manage it directly in the `Hero`. However, to avoid creating a huge PR, we go step by step.

### CODE REVIEW

**Comment by AntonioVentilii-DFINITY** [comment]
[OISY-64]

**Review by peterpeterparker — COMMENTED** [review]
As you mention that you are planing multiple PRs to bubble props, have you though about a context and would it avoid too many level of properties drilling? Or does not make sense here?

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker I actually first thought of a global store/derived eheh! Never thought about the context, but it most probably be quite the same; shall I have a try at it and come back to you?

**Comment by peterpeterparker** [comment]
> it most probably be quite the same; shall I have a try at it and come back to you?

Worth having a look if there is 3 or 4 level down of passing properties but, sure if it's just one or two, that's maybe an overkill.

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker I think it is better! Good suggestion! Have a look:

- PR #3276

**Comment by AntonioVentilii-DFINITY** [comment]
This was superseded by PR #3276 , as discussed above

**Pull request closed without merging**
