### PR TITLE
chore: Docker container for e2e backend

### PR DESCRIPTION
**Pull request by peterpeterparker**
# Motivation

For our E2E tests, my idea is to run Playwright tests against a Docker container that contains and runs all canisters and other features that make up Oisy.

This PR initializes the first version of such a container.

At build time, the required dependencies are installed, and all canisters are deployed to a local replica, including Oisy's backend. At runtime, the container resumes with the state that was built.

I took this approach assuming that we would be able to publish the image somewhere and also assuming that deploying the canisters takes time.

Currently, any changes in the backend would require rebuilding the entire container.

We might change this approach iteratively. Again, this is a first draft.

# Commands

Build:

```
docker build . --file Dockerfile.e2e -t oisy-wallet-dev --progress=plain  --platform=linux/amd64
```

Run:

```
docker run -p 4943:4943 oisy-wallet-dev
```

Stop:

```
docker stop $(docker ps -aq)
``` 

# Changes

- New `Dockerfile.e2e` and scripts to deploy and start dfx
- Add a `.dockerignore` file to only copy what we need from the project within the container
- Add a `mkdir` in the deploy script given that the targetted folder to download the wasm files might not exist.
- Add also a `wait-for` script which can be used to wait for ports to be mounted. Useful to wait for the replica and icx-proxy.

# Tests

### CODE REVIEW

**Review by AntonioVentilii-DFINITY — APPROVED** [review]
Very cool! LGTM!

**Review by bitdivine — COMMENTED** [review]
Looks good!  Does it work?

**Comment by peterpeterparker** [comment]
> Looks good! Does it work?

Yes. It exposes same port as DFX so we can validate by running `npm run dev` against it.

**Comment by peterpeterparker** [comment]
Discussed offlien yesterday with @bitdivine who accepted the PR but, forgot to hit the "Accept" button 😉.
Therefore, I'll merge this PR.

**Pull request merged**
