### PR TITLE
feat(frontend): Set up Bitcoin transactions page

### PR DESCRIPTION
**Pull request by lmuntaner**
# Motivation

The transactions page for Bitcoin was not showing balance, nor logo, nor nice background.

The error was that it didn't find any token in the pageToken derived store and that the btc didn't have any assigned background.

# Changes

* Add the bitcoin tokens as the tokens to search the pageToken.
* Set up a BtcTransactions component.
* Add a background in the Hero for the Bitcoin network. (To be determined with design which one, but for now, same as ICP).
* Render BtcTransactions if network is BTC.
* New derived store `networkBitcoin`.

# Tests

Tested manually that Hero appears as expected.

### CODE REVIEW

**Comment by lmuntaner** [comment]
Before:

Screenshot 2024-09-02 at 15 32 23

This PR:

Screenshot 2024-09-02 at 15 30 31

**Review by peterpeterparker — COMMENTED** [review]
Can you provide this in two separate PRs please? e.g. stores part followed by UI usage

**Comment by lmuntaner** [comment]
> Can you provide this in two separate PRs please? e.g. stores part followed by UI usage

Sure, I love small PRs. First one: https://github.com/dfinity/oisy-wallet/pull/2214

What is the rule to know when a PR is the right size? A PR can only touch one layer like api, services, components, etc? Or is it common sense?

**Comment by peterpeterparker** [comment]
> What is the rule to know when a PR is the right size? A PR can only touch one layer like api, services, components, etc? Or is it common sense?

I'm not sure what the informal rule is. It’s a bit like grouping small PRs and related changes together. In this particular PR, the concern is with the stores, as we've recently had issues with an endless loop involving derived stores.

Perhaps @AntonioVentilii-DFINITY has a better definition?

**Comment by AntonioVentilii-DFINITY** [comment]
I usually base them more on single revertable (or modifiable) changes.  For example, in this case, the `Hero` background would go in a different PR, even if small. Just because we could revert or change it after merging, and it would have a simpler history. 
I'm not really sure if I explained correctly. 

P.S. for me, it is even easier to follow: I submit 5 small PRs at the same time, and if there is a review in one of them, the others are not blocked. Plus, I can change them independently and really verify that one does not affect the other, unrelated (that always means good)

**Comment by lmuntaner** [comment]
Closing in favor of #2223 and #2214

**Pull request closed without merging**
