### PR TITLE
refactor(frontend): move hide info utils to common folder

### PR DESCRIPTION
**Pull request by AntonioVentilii**
# Motivation

Since we are going to re-use them, we move the hide info utils to the common `lib` folder. And we add tests.

# Note

I am not using zod for the keys list because I am replicating the way we do for modals, defining explicit string types. I am not 100% sure that zod enforces the strings in the same way.

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
The PR description says "move" but, things are also renamed. Should it be two PRs?

**Comment by AntonioVentilii** [comment]
@peterpeterparker you are right, I will do the rename in another PR

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Comment by AntonioVentilii** [comment]
[OISY-130]

**Pull request merged**
