### PR TITLE
refactor: changed function decodeQrCode to use interal decodeQrCodeUrn

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

Instead of using the `decodePayment` function from package `@dfinity/ledger-icrc`, we will use the function `decodeQrCodeUrn` that treats a broader spectrum of tokens and transactions.

# Changes

- Changed the decoding function in `decodeQrCode`.
- Created an internal method to match specific Ethereum tokens based on the decoded QR code..

# Tests

Modified the original test of `decodeQrCode` to adapt to the new code.

### CODE REVIEW

**Comment by AntonioVentilii-DFINITY** [comment]
> For ICP/ICRC, I think we should continue to use `decodePayment` as this function will be reviewed/improved when the standard is accepted and because we want to use the same libraries for the IC as we and the community do.

So, do you think it is better to put separate QR decoding functions in each folder `frontend/src/icp` and `frontend/src/eth`, or shall I treat it in the common function with some IF condition?

**Comment by peterpeterparker** [comment]
> So, do you think it is better to put separate QR decoding functions in each folder 

Yes, I would go for separation of concern with `frontend/src/icp` and `frontend/src/eth`

**Comment by AntonioVentilii-DFINITY** [comment]
I will move this to a draft while I work separately on it with #1356

**Comment by AntonioVentilii-DFINITY** [comment]
Closed this one and opened PR #1359

**Pull request closed without merging**
