### PR TITLE
feat(frontend):move filter to derived function

### PR DESCRIPTION
**Pull request by darioloetsc**
# Motivation

Preparation for group view integration.

# Changes

Moving the filter to derived function needs to be wrapped again later.

# Tests

None

### CODE REVIEW

**Review by AntonioVentilii-DFINITY — COMMENTED** [review]
Before reviewing, maybe I missed a step: are you not going to use the tokens list that `TokensDisplayHandler` provides? Meaning, is it not the grouping being done directly inside the `TokensSignedIn` component's list?

**Comment by AntonioVentilii-DFINITY** [comment]
@darioloetsc thank you for the explanation! Then why should the balance filter be moved to a separate derived store? For example, why not using directly `sortedTokens` list

**Comment by darioloetsc** [comment]
Please provide a change request, sry I cannot follow. The idea of this commit is to make it easier for later mapping and not pile wrappers within the handler. If you have a better idea of how to clean up the handler, please go ahead.

**Comment by darioloetsc** [comment]
As discussed, we dont do it. To many derived chained.

**Pull request closed without merging**
