### PR TITLE
feat(frontend): remove FET token

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

We were asked to remove the FET token.

### CODE REVIEW

**Review by peterpeterparker — APPROVED** [review]
Code wise, LGTM. Thx.

~~I wonder if any users have transferred FET to their Oisy Wallet and will end up having their funds stuck there. I guess we will know once it's live.~~

**Comment by peterpeterparker** [comment]
Updated the title of the PR from `refactor(frontend)` to `feat(frontend)!` to reflect the fact that this is breaking change.

**Comment by AntonioVentilii-DFINITY** [comment]
> I wonder if any users have transferred FET to their Oisy Wallet and will end up having their funds stuck there. I guess we will know once it's live.

They can still add the token manually, right?

**Comment by peterpeterparker** [comment]
> They can still add the token manually, right?

RIGHT! Thanks.

Removed the `!` from the title.

**Pull request merged**
