### PR TITLE
feat(frontend): New public routes

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

We would like to have "public" routes in OISY, for example for Terms and Conditions. So, we set an independent page, agnostic to signed in or not.

Screenshot 2024-10-25 at 12 48 55

### CODE REVIEW

**Review by peterpeterparker — APPROVED** [review]
Looks good, already approving.

Just a question: it was requested to name the route `/terms-and-conditions`? not just `/terms`?

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker no compulsory specification actually, but this was like that in the requirements. I just asked the Design team + Legal and they say to go with `/terms-and-conditions`, even if they checked that some other app uses just `/terms`

**Comment by AntonioVentilii-DFINITY** [comment]
[OISY-122]

**Comment by peterpeterparker** [comment]
> even if they checked that some other app uses just 

Indeed `/terms` and `/privacy` are quite common I got the feeling. Thanks for the feedback.

**Pull request merged**
