### PR TITLE
chore(frontend): Remove Unused Svelte Files

### PR DESCRIPTION
**Pull request by sa-github-api**
The following files were removed because they were not used in the project anymore:
```
src/frontend/src/btc/components/send/BtcReviewNetwork.svelte
src/frontend/src/icp/components/send/IcReviewNetwork.svelte
src/frontend/src/lib/components/send/ReviewNetwork.svelte
src/frontend/src/lib/components/send/SendBtcNetwork.svelte
```

### CODE REVIEW

**Comment by peterpeterparker** [comment]
@DenysKarmazynDFINITY it's maybe related to your recent changes to the Send wizard modal? Are those still used?

**Comment by AntonioVentilii-DFINITY** [comment]
Maybe we should ignore this without merging this week, until Bitcoin gestire feature is released?

**Comment by peterpeterparker** [comment]
@DenysKarmazynDFINITY ?

**Comment by DenysKarmazynDFINITY** [comment]
Sorry, missed the notification here. 2 of those components are actually in use, the other 2 - I will fix it in a separate PR. After that, we can close this one.

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker @DenysKarmazynDFINITY I will actually close this one because I just [re-run the workflow manually](https://github.com/dfinity/oisy-wallet/actions/runs/11365002408) on main and it gave no unused components

I imagine that one of the latest PR made it so they are all used again

**Pull request closed without merging**
