### PR TITLE
ci(e2e): adjust playwright config

### PR DESCRIPTION
**Pull request by inc-man**
# Motivation

We want to add more devices to the tests and adjust different timeouts so we can handle them in a better way.

# Changes

- added macOS config
- added more devices
- added timeouts

# Tests

- tested on branch

### CODE REVIEW

**Review by AntonioVentilii — COMMENTED** [review]
I would prefer to separate this PR:

- timeout
- devices

and for devices, it should provide the new screenshots, after having ran the CI workflow

**Comment by inc-man** [comment]
okay so I break it up into 3 different PRs. Screenshots will be automatically added with the update-snapshots workflow after everything is merged no?

**Comment by AntonioVentilii** [comment]
> after everything is merged no?

you should run it manually on your branch before merging, as test to see if everything works correctly

**Comment by inc-man** [comment]
broken up into 3 different PRs

**Pull request closed without merging**
