### PR TITLE
chore(IDX): replace PAT with GitHub App

### PR DESCRIPTION
**Pull request by cgundy**
# Motivation

This is part of a larger effort to replace PATs generated my service accounts with GitHub Apps.

# Changes

No functional changes.

# Tests

No tests run, but has been successfully installed in other repos.

### CODE REVIEW

**Review by AntonioVentilii — COMMENTED** [review]
@cgundy thank you for this! Do you think it makes sense that it becomes an action instead of a step in each workflow? Just to avoid repetition of code

**Comment by cgundy** [comment]
@AntonioVentilii do you mean like a composite action? I'm not sure I understand.

**Comment by AntonioVentilii** [comment]
@cgundy yes, correct! a composite. I see you changed it in a few CIs. I am just asking if it is possible at all eheh!

**Review by AntonioVentilii — APPROVED** [review]
LGTM tks!

**Pull request merged**
