### PR TITLE
style(frontend): favicon with rounded corners

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

New favicon with rounded corners.

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Not all icons can have rounded corner. e.g. Android expect maskable icons.

**Comment by AntonioVentilii-DFINITY** [comment]
> Not all icons can have rounded corner. e.g. Android expect maskable icons.

@artkorotkikh-dfinity do you want to maybe have a look before we merge?

**Comment by artkorotkikh-dfinity** [comment]
@peterpeterparker , @AntonioVentilii-DFINITY Is there anything I can do to address the maskable icon comment?

**Comment by peterpeterparker** [comment]
> Is there anything I can do to address the maskable icon comment?

My only point is that maskable icons are the best practice nowadays for modern Android devices and Google products. An icon with rounded corners is not a maskable icon.

For example, [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Define_app_icons#support_masking).

> The following image illustrates the difference between a maskable and a non-maskable icon on Android:
image

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker @artkorotkikh-dfinity if you want I can make them maskable and add them in the manifest:
```json
"icons": [
    {
      "src": "favicons/icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "favicons/icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "favicons/maskable-icon-192x192.png",
      "sizes": "192x192",
      "type": "image/png",
      "purpose": "maskable"
    },
    {
      "src": "favicons/maskable-icon-512x512.png",
      "sizes": "512x512",
      "type": "image/png",
      "purpose": "maskable"
    }
  ]
```

**Comment by peterpeterparker** [comment]
Yes.

Personaly, I would probably also keep the favicon as not rounded corner as I'm unsure if those are not cropped on some devices and browsers, but we can give it a try.

**Comment by AntonioVentilii-DFINITY** [comment]
Done:

- PR #1954

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Pull request merged**
