### PR TITLE
style(frontend): expand space available for main title

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

As per request, we expand the main title to occupy the available space.

### Before

Screenshot 2024-08-21 at 14 47 53

### After

Screenshot 2024-08-21 at 14 47 44

### CODE REVIEW

**Comment by DenysKarmazynDFINITY** [comment]
@AntonioVentilii-DFINITY just a friendly reminder to run https://github.com/dfinity/oisy-wallet/actions/workflows/update-snapshots.yml against your branch to update the snapshots. I also just noticed that we launch e2e-tests check only when the files in `e2e` folder have changed, the behaviour to be changed as we are getting more and more test suites, I'll take care of it.

**Comment by peterpeterparker** [comment]
How does it looks like on really large screen, like a single line? Shouldn't we set a max-width to occupy two lines?

**Comment by AntonioVentilii-DFINITY** [comment]
It is already limited by one of the parents:

Screenshot 2024-08-21 at 17 44 04

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks

**Comment by AntonioVentilii-DFINITY** [comment]
@DenysKarmazynDFINITY thank you for the heads-up! I will run the workflow on this branch, but I am pretty sure that other PRs (already merged) have affected the test...

I agree, it should set up in a sort of automatic way

**Pull request merged**
