### PR TITLE
refactor(frontend): generalize Info banner component

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

Since we are going to reuse it even for ETH/ERC20 tokens, we generalize the usage if the `Info` component.

# Changes

- Move `infoBox` to `lib/components/info`.
- Create component `InfoBanner` that just accepts `key` as prop and manage the show/hide features (this part was already in `Info` component, and it was just separated).
- Adapt `Info` component.

# Tests

No changes in local replica.

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
Can we find a better name that `InfoBanner` as this component isn't a banner?

**Comment by AntonioVentilii-DFINITY** [comment]
Maybe `InfoWrapper`?

**Comment by peterpeterparker** [comment]
Why not, or `InfoBoxWrapper`.

**Comment by AntonioVentilii-DFINITY** [comment]
Done

**Review by peterpeterparker — APPROVED** [review]
LGTM; thx

**Pull request merged**
