### PR TITLE
feat(ci): auto-update package-lock file

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

it would be useful to have a check/action that auto-updates the `package-lock.json` file if there is a need for it if `package.json` has changed.

### CODE REVIEW

**Comment by peterpeterparker** [comment]
I would say not until we got tests. There might be often updates and each of those will need tests.

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker then I will leave as draft for now

**Comment by AntonioVentilii-DFINITY** [comment]
yes yes, agreed, makes sense. I will just leave it here as draft otherwise I end up forgetting it

**Comment by AntonioVentilii** [comment]
Since it was my old account, it is superseded by:

- PR #

**Pull request closed without merging**
