### PR TITLE
feat(frontend): Buy button is visible but disabled

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

We change the visibility of the Buy button making it always visible but disabled, pending the completion of OnRamper onboarding.

Screenshot 2024-09-23 at 06 26 47
Screenshot 2024-09-23 at 06 26 54

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Product decision?

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker indeed

**Comment by peterpeterparker** [comment]
I see. And what does "disabled" mean? Is there any plan to provide some hints to the user about why this button is always disabled? If not, are we fine user not knowing why?

**Comment by AntonioVentilii-DFINITY** [comment]
shall i maybe add a tooltip that is triggered on click? @anedos-dfinity WDYT?

**Comment by anedos-dfinity** [comment]
I think it's fine for now, in the next version we'll work on onramper.com support so we'll have a functional button pretty soon.

**Review by peterpeterparker — APPROVED** [review]
Rubber stamp. This is weak UX.

**Pull request merged**
