### PR TITLE
feat(frontend): store with ck twin token for Ethereum tokens

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

It will come useful to have a derived store that provides the possible ck-twin-token for the current selected token.

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
The ultimate goal is to remove the deprecated `tokenWithFallback` so, I'm not sure we should add more derived store at the top. WDYT?

**Comment by AntonioVentilii-DFINITY** [comment]
Yes, agreed! But shall I use `token` store instead?

**Comment by peterpeterparker** [comment]
If you are agree, then I would say we don't need this PR. If this PR was meant to avoid code duplication for future PR, can you describe which features?

**Comment by AntonioVentilii-DFINITY** [comment]
Let me revisit then, closing for now

**Pull request closed without merging**
