### PR TITLE
style(frontend): change scrollbar style [GIX-3019]

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

New scrollbar style.

### Before

https://github.com/user-attachments/assets/87c7491b-c779-49bf-aec7-a4bfee3d656f

### After

https://github.com/user-attachments/assets/343a5994-41ac-4b1b-a95b-86f5f6c2cfbe

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
Did you test in Chrome, Safari and Firefox?

**Comment by AntonioVentilii-DFINITY** [comment]
- Chrome: yes, it's the video in the description
- Safari: i reduced a bit the border opacity, jut to make it more immediate (it is not so clear as before, but it is noticable)
- Firefox: we don't set the scrollbar color, to do that we need to change the native one:

```
html {
    scrollbar-width: ...
    scrollbar-color: ....
}
```

shall I do it here or in another PR?

**Comment by peterpeterparker** [comment]
Let's do everything here. Thanks for double checking.

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker I am having an issue setting it for Foirefox (and I think that is the reason why we don't do it):

according to [documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling), there is not much you can change with the scrollbar: in our case only color and width. However the width has fixed parameter, and if I set it and the color, it will overwrite the rest:

```css
::-webkit-scrollbar-thumb {
	background-color: var(--color-misty-rose);
}

::-webkit-scrollbar-track {
	border-radius: 0;
	background: none;
}

::-webkit-scrollbar {
	width: 0.45rem;
}
```

any idea? I tried a few things, but it seems a know behavior

**Comment by peterpeterparker** [comment]
Thanks for trying. Let's just implement the best we can for Firefox (or nothing if nothing is posible) and we review it later if necessary.

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker perfect, then in this case, I will leave it as it is, but I added a TODO for the future

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

**Pull request merged**
