### PR TITLE
style(frontend): include logos for new ERC20 tokens

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

For the new ERC20 tokens included with PR #1740 , we add the logos.

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
weeth.svg is heavy and dmail to some extension a bit as well? can we spare some kb there?

**Comment by AntonioVentilii-DFINITY** [comment]
let me reduce them

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks

Note that I assume we can use those icons - i .e. that none of those are copyrighted or so and none are requiring some forms of explicit mention of usage.

**Comment by AntonioVentilii-DFINITY** [comment]
indeed! I went through the websites / github pages, and some other source (a mix of trustwallet and CNC), and I took the versions that were usable/available.

Either way, we will substitute them with the ck* icon when it become available

**Comment by peterpeterparker** [comment]
Thanks Antonio!!!

**Pull request merged**
