### PR TITLE
style(frontend): update welcome banner logo

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

New banner logo.

Screenshot 2024-07-24 at 14 58 43

### CODE REVIEW

**Review by peterpeterparker — APPROVED** [review]
LGTM, thanks.

Note that the size is doubling (46kb to 113kb).

**Comment by artkorotkikh-dfinity** [comment]
It was the raster layer with noise. I replaced it with just a dark overlay and saved 100kb: 
Feel free to use this optimized svg: 
 
optimized-banner

**Comment by AntonioVentilii-DFINITY** [comment]
Updated with latest version of 26kb

**Comment by peterpeterparker** [comment]
Nice! Thanks

**Comment by AntonioVentilii-DFINITY** [comment]
tks @artkorotkikh-dfinity !

**Pull request merged**
