### PR TITLE
refactor(frontend): change layout of main token list [GIX-3046]

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

We shift a few elements of the Token list around: basically the amounts (balance and fiat) go to the right, and symbol and name go to the left.

Note: we must be careful because a few modified components are used elsewhere too, but the screenshots seems to be ok.

# Changes

- Create UI component `CardSubAmount` to include in the `Card` component.
- Assign new slots in `TokenCard`:
  - `balance` goes in the top-right side;
  - `exchange` goes to the bottom-right side;
  - token `symbol` goes as main name in the top-left side;
  - token `name` goes as `description` in the bottom-left side.
- Remove the token `symbol` from the `balance`.

# Tests

Screenshot 2024-10-07 at 19 05 26
Screenshot 2024-10-07 at 19 05 38
Screenshot 2024-10-07 at 19 05 44
Screenshot 2024-10-07 at 19 05 56
Screenshot 2024-10-07 at 19 06 21
Screenshot 2024-10-07 at 19 06 39

# Other instances where the component `Card` is used

Screenshot 2024-10-07 at 19 09 26
Screenshot 2024-10-07 at 19 10 07
Screenshot 2024-10-07 at 19 10 15

### CODE REVIEW

**Comment by peterpeterparker** [comment]
Have you fake the views with large amounts and large texts? Does the display still look good?

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker I thought the ones in the screenshots were large eheh! But I will check for larger!

BTW, I think we should reduce how we write the numbers for bigger number, for example, above 5 millions

**Comment by AntonioVentilii-DFINITY** [comment]
@peterpeterparker these are some fake big numbers, WDYT?

Screenshot 2024-10-08 at 10 55 42
Screenshot 2024-10-08 at 10 56 41
Screenshot 2024-10-08 at 10 58 18

**Review by peterpeterparker — APPROVED** [review]
LGTM, thx

PS: don't have better idea than `subAmount` but I thought about it a bit

**Pull request merged**
