### PR TITLE
feat(frontend): info box for ck conversions in Ethereum tokens

### PR DESCRIPTION
**Pull request by AntonioVentilii-DFINITY**
# Motivation

The info box about ck conversions will be shown in the twin tokens of ETH/ERC20 tokens too.

# Changes

- Create new `Info` component for Ethereum (similar to the one for IC)
- Include component into `Transactions` page.

# Tests

Screenshot 2024-08-25 at 14 55 56
Screenshot 2024-08-25 at 14 56 24

### CODE REVIEW

**Review by peterpeterparker — COMMENTED** [review]
Wait, do I understand correctly that you want to display the InfoBox currently shown on ckETH and ckERC20 on ETH and ERC20?

If so, aren't we about to mix ICP and ETH-related components, since the InfoBox includes a call to action that opens a modal explaining how to convert the selected Ethereum token?

And if we're mixing those components, are you sure that all the necessary data will be loaded when displayed on Ethereum as well?

Have you tested all these cases and business flows?

Or am I misunderstanding something?

**Comment by AntonioVentilii-DFINITY** [comment]
> Wait, do I understand correctly that you want to display the InfoBox currently shown on ckETH and ckERC20 on ETH and ERC20?

Correct! However this is still a draft, I made a mistake moving it to review, sorry. It still depends on other PRs.

**Comment by peterpeterparker** [comment]
Thanks. As discussed with @anedos-dfinity, let's postpone displaying those boxes on ETH/ERC20 and implementing everything needed for their related conversion flows for a few weeks.

**Comment by AntonioVentilii** [comment]
this PR is deprecated, since we are not interested in show the info box anymore

**Pull request closed without merging**
